language: clojure
lein: lein
jdk:
- openjdk8
before_install:
- git config --global user.email "ohyecloudy@gmail.com"
- git config --global user.name "ohyecloudy"
install:
- git clone https://$GH_TOKEN@github.com/ohrepos/quotes-repo.git --branch=gh-pages result
- git clone https://github.com/ohyecloudy/tbot-quote-builder.git builder
- cd builder;lein uberjar
script:
- cd ..;java -jar ./builder/target/tbot-quote-builder-standalone.jar -s ./src/q-src.clj -o ./result/quotes -b http://ohrepos.github.io/quotes-repo/quotes/ -t @bquote_bot
after_success:
- cd result
- git remote rm origin
- git remote add origin https://$GH_TOKEN@github.com/ohrepos/quotes-repo.git
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
- git push -fq origin gh-pages
env:
  global:
  - secure: Si9l2FrGp1RkGkIrsAGgL2K8O1cK16wrjFkeSC963I59R6CWungaSAZVg/qTgUVBrK/7+5cVvhsuU+g484HcxRxR0qOH8SDw32csfNXzYFwc3anywzlvU7wgHmS7i5CzuAAHhLL7+OklJ+cXOeZSNt9nqxYVvW3VuMQpPwOcSHs=
