language: java
jdk:
- openjdk7
before_install:
- git config --global user.email "ohyecloudy@gmail.com"
- git config --global user.name "ohyecloudy"
install:
- git clone     https://ohyecloudy:$GH_TOKEN@github.com/ohrepos/quotes-repo.git --branch=gh-pages result
- curl -O -L https://github.com/ohyecloudy/tbot-800/releases/download/v0.1.0/quote-builder-800-0.1.0-SNAPSHOT-standalone.jar
script:
- java -jar quote-builder-800-0.1.0-SNAPSHOT-standalone.jar -s ./src/q-src.clj -o ./result/quotes -b http://ohrepos.github.io/quotes-repo/quotes/ -t @bquote_bot
after_success:
- cd result
- git remote rm origin
- git remote add origin https://ohyecloudy:$GH_TOKEN@github.com/ohrepos/quotes-repo.git
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
- git push -fq origin gh-pages

env:
  global:
    secure: JrwHEzWkBDm7SFPVw+4uCRqHe5Wlp7nmgOgM3OxnIWLFsnd9Cxx06tasQPufQqnEEyYEpWabkggqxDnYSNiKS0KhWWDpFnaJE16yegx2YB0pI9bSq5FGumKDUBhrK9X7M1OdKLexu/AcHvh9ztfZTRs+l0FARxVffR5Phb4maU8= 

